### ISSUE TITLE
1.3.4 needed but crashed

### ISSUE THREAD

**Issue by kaidenmoe** [SrRapero720/watermedia#55]
I am trying to add this to my 1.20.1 world and it auto-installs version 2.0 of this mod on curseforge, You get the prompt when booting up you need 1.3.4 instead. when you switch to this version you get the error exit code: -1 message screen.

The game crashed whilst initializing game
Error: java.lang.NullPointerException: Initializing game
-1

**Comment by SrRapero720** [comment]
Install WaterFrames 2.0-beta5.1 to use watermedia 2.0.x
